name: Daily Exchange Rate Mailer

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 1:00 运行 (根据需要调整时间)
  workflow_dispatch:  # 允许手动触发

jobs:
  send-exchange-rate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run exchange rate mailer script
      env:
        EMAIL_PROVIDER: ${{ secrets.EMAIL_PROVIDER }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python exchange_rate_mailer.py
